version: '3.1'

services:

  wordpress:
    image: wordpress
    restart: always
    ports:
      - 16000:80
    environment:
      WORDPRESS_DB_PASSWORD: samplepassword

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: samplepassword